# Generated by Django 4.0.4 on 2022-05-19 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('distance', models.IntegerField()),
                ('time', models.DurationField()),
                ('image', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Indoor'), ('T', 'Track')], default='O', max_length=1)),
                ('gear', models.ManyToManyField(to='main_app.gear')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.run')),
            ],
        ),
    ]
