# Generated by Django 4.0.4 on 2022-05-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_gear_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='image',
            field=models.CharField(default='https://i.imgur.com/Puwhno0.jpg', max_length=100),
        ),
    ]
