# Generated by Django 4.0.4 on 2022-05-24 00:36

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(default=main_app.models.default_run_name, max_length=50),
        ),
    ]
