# Generated by Django 4.0.4 on 2022-05-27 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_gear_image_alter_run_date_alter_run_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
