# Generated by Django 4.0.4 on 2022-05-30 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_gear_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='image',
        ),
        migrations.AddField(
            model_name='gear',
            name='type',
            field=models.CharField(choices=[('S', 'Shoes'), ('H', 'Heartrate-monitor'), ('W', 'Watch'), ('B', 'Bottle'), ('O', 'Other')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='gear',
            name='brand',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(default='Evening Run', max_length=50),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.run')),
            ],
        ),
    ]
