# Generated by Django 4.0.4 on 2022-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_run_image_gear_type_alter_gear_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(default='Afternoon Run', max_length=50),
        ),
    ]
